begin;

create extension if not exists pgcrypto;

-- =========================
-- 1) CORE TABLES
-- =========================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  preferred_model text not null default 'model00000',
  created_at timestamptz not null default timezone('utc', now()),
  constraint profiles_email_has_at check (position('@' in email) > 1),
  constraint profiles_preferred_model_allowed check (
    preferred_model in (
      'model00000', 'model00001', 'model00010', 'model00011', 'model00100',
      'model00101', 'model00110', 'model00111', 'model01000', 'model01001',
      'model01010'
    )
  )
);

alter table public.profiles
add column if not exists preferred_model text not null default 'model00000';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_preferred_model_allowed'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
    add constraint profiles_preferred_model_allowed check (
      preferred_model in (
        'model00000', 'model00001', 'model00010', 'model00011', 'model00100',
        'model00101', 'model00110', 'model00111', 'model01000', 'model01001',
        'model01010'
      )
    );
  end if;
end $$;

create table if not exists public.characters (
  id smallint primary key,
  name text not null unique,
  description text not null,
  model_path text not null,
  image_path text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint characters_id_range check (id between 1 and 11)
);

create table if not exists public.cards (
  id integer generated by default as identity primary key,
  character_id smallint not null references public.characters(id) on delete cascade,
  card_index smallint not null,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint cards_index_range check (card_index between 0 and 7),
  constraint cards_character_index_unique unique (character_id, card_index)
);

create table if not exists public.user_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  card_id integer not null references public.cards(id) on delete cascade,
  unlocked boolean not null default false,
  unlocked_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint user_cards_user_card_unique unique (user_id, card_id),
  constraint user_cards_unlock_consistency check (
    (unlocked = true and unlocked_at is not null)
    or
    (unlocked = false and unlocked_at is null)
  )
);

create table if not exists public.user_characters (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_id smallint not null references public.characters(id) on delete cascade,
  unlocked boolean not null default false,
  unlocked_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint user_characters_user_character_unique unique (user_id, character_id),
  constraint user_characters_unlock_consistency check (
    (unlocked = true and unlocked_at is not null)
    or
    (unlocked = false and unlocked_at is null)
  )
);

create table if not exists public.play_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_date timestamptz not null default timezone('utc', now()),
  score integer not null default 0,
  puzzles_solved integer not null default 0,
  duration_seconds integer not null default 0,
  constraint play_history_score_non_negative check (score >= 0),
  constraint play_history_puzzles_non_negative check (puzzles_solved >= 0),
  constraint play_history_duration_non_negative check (duration_seconds >= 0)
);

-- =========================
-- 2) PERFORMANCE INDEXES
-- =========================

create index if not exists idx_user_cards_user_id on public.user_cards(user_id);
create index if not exists idx_user_cards_card_id on public.user_cards(card_id);
create index if not exists idx_cards_character_id on public.cards(character_id);
create index if not exists idx_user_characters_user_id on public.user_characters(user_id);
create index if not exists idx_user_characters_character_id on public.user_characters(character_id);
create index if not exists idx_play_history_user_id on public.play_history(user_id);
create index if not exists idx_play_history_user_id_session_date on public.play_history(user_id, session_date desc);
create index if not exists idx_user_cards_user_unlocked on public.user_cards(user_id, unlocked) where unlocked = true;
create index if not exists idx_user_characters_user_unlocked on public.user_characters(user_id, unlocked) where unlocked = true;

-- =========================
-- 3) RLS (SUPABASE SAFE DEFAULTS)
-- =========================

alter table public.profiles enable row level security;
alter table public.characters enable row level security;
alter table public.cards enable row level security;
alter table public.user_cards enable row level security;
alter table public.user_characters enable row level security;
alter table public.play_history enable row level security;

-- profiles: each user reads/updates own row
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- static tables: readable to authenticated and anon users
drop policy if exists characters_select_all on public.characters;
create policy characters_select_all
  on public.characters for select
  using (true);

drop policy if exists cards_select_all on public.cards;
create policy cards_select_all
  on public.cards for select
  using (true);

-- user_cards: owner-only access
drop policy if exists user_cards_select_own on public.user_cards;
create policy user_cards_select_own
  on public.user_cards for select
  using (auth.uid() = user_id);

drop policy if exists user_cards_update_own on public.user_cards;
create policy user_cards_update_own
  on public.user_cards for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- user_characters: owner-only access
drop policy if exists user_characters_select_own on public.user_characters;
create policy user_characters_select_own
  on public.user_characters for select
  using (auth.uid() = user_id);

drop policy if exists user_characters_update_own on public.user_characters;
create policy user_characters_update_own
  on public.user_characters for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- play_history: owner-only select/insert
drop policy if exists play_history_select_own on public.play_history;
create policy play_history_select_own
  on public.play_history for select
  using (auth.uid() = user_id);

drop policy if exists play_history_insert_own on public.play_history;
create policy play_history_insert_own
  on public.play_history for insert
  with check (auth.uid() = user_id);

-- =========================
-- 4) TRIGGER FUNCTIONS
-- =========================

-- IMPORTANT: this function is called from user_cards unlock trigger and can be called manually.
create or replace function public.unlock_character_if_completed(
  p_user_id uuid,
  p_character_id smallint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total_cards integer;
  v_unlocked_cards integer;
begin
  select count(*)
  into v_total_cards
  from public.cards c
  where c.character_id = p_character_id;

  if v_total_cards = 0 then
    return;
  end if;

  select count(*)
  into v_unlocked_cards
  from public.user_cards uc
  join public.cards c on c.id = uc.card_id
  where uc.user_id = p_user_id
    and c.character_id = p_character_id
    and uc.unlocked = true;

  if v_unlocked_cards = v_total_cards then
    update public.user_characters uch
    set unlocked = true,
        unlocked_at = coalesce(uch.unlocked_at, timezone('utc', now()))
    where uch.user_id = p_user_id
      and uch.character_id = p_character_id
      and uch.unlocked = false;
  end if;
end;
$$;

create or replace function public.handle_user_card_unlock_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_character_id smallint;
begin
  if new.unlocked = true and (tg_op = 'INSERT' or old.unlocked is distinct from true) then
    select c.character_id
    into v_character_id
    from public.cards c
    where c.id = new.card_id;

    if v_character_id is not null then
      perform public.unlock_character_if_completed(new.user_id, v_character_id);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_user_cards_unlock_character on public.user_cards;
create trigger trg_user_cards_unlock_character
after insert or update of unlocked on public.user_cards
for each row
when (new.unlocked = true)
execute function public.handle_user_card_unlock_trigger();

-- Create profile + initial locked collection rows when auth.users row is created.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, preferred_model)
  values (new.id, coalesce(new.email, ''), 'model00000')
  on conflict (id) do update
  set email = excluded.email;

  insert into public.user_characters (user_id, character_id, unlocked, unlocked_at)
  select new.id, c.id, false, null
  from public.characters c
  on conflict (user_id, character_id) do nothing;

  insert into public.user_cards (user_id, card_id, unlocked, unlocked_at)
  select new.id, c.id, false, null
  from public.cards c
  on conflict (user_id, card_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_auth_user_created on auth.users;
create trigger trg_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();

-- Keep profile.email synchronized if auth.users.email changes.
create or replace function public.sync_profile_email_from_auth_users()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set email = coalesce(new.email, '')
  where id = new.id;

  return new;
end;
$$;

drop trigger if exists trg_auth_user_email_updated on auth.users;
create trigger trg_auth_user_email_updated
after update of email on auth.users
for each row
execute function public.sync_profile_email_from_auth_users();

-- Backfill support if static content is added later.
create or replace function public.seed_user_characters_for_new_character()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_characters (user_id, character_id, unlocked, unlocked_at)
  select p.id, new.id, false, null
  from public.profiles p
  on conflict (user_id, character_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_character_seed_user_characters on public.characters;
create trigger trg_character_seed_user_characters
after insert on public.characters
for each row
execute function public.seed_user_characters_for_new_character();

create or replace function public.seed_user_cards_for_new_card()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_cards (user_id, card_id, unlocked, unlocked_at)
  select p.id, new.id, false, null
  from public.profiles p
  on conflict (user_id, card_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_card_seed_user_cards on public.cards;
create trigger trg_card_seed_user_cards
after insert on public.cards
for each row
execute function public.seed_user_cards_for_new_card();

-- =========================
-- 5) STATIC SEED DATA (11 CHARACTERS, 88 CARDS)
-- =========================

insert into public.characters (id, name, description, model_path, image_path)
values
  (1,  'Arlecchino', 'Crimson tactician with high-risk precision combat style.', 'model00001.vrm', '/character-img-00001.png'),
  (2,  'Charlotte',  'Investigative reporter using sharp insight and support utility.', 'model00010.vrm', '/character-img-00010.png'),
  (3,  'Furina',     'Hydro performer controlling rhythm, pressure, and adaptation.', 'model00011.vrm', '/character-img-00011.png'),
  (4,  'Ganyu',      'Calm cryo archer focused on timing and sustained precision.', 'model00100.vrm', '/character-img-00100.png'),
  (5,  'Keqing',     'Electro duelist built around burst movement and rapid execution.', 'model00101.vrm', '/character-img-00101.png'),
  (6,  'Kokomi',     'Strategic hydro leader with balanced sustain and control.', 'model00110.vrm', '/character-img-00110.png'),
  (7,  'Nahida',     'Dendro analyst linking systems through layered reactions.', 'model00111.vrm', '/character-img-00111.png'),
  (8,  'Navia',      'Geo commander specializing in momentum and tactical shots.', 'model01000.vrm', '/character-img-01000.png'),
  (9,  'Neuvillette','Hydro judge channeling heavy pressure and field dominance.', 'model01001.vrm', '/character-img-01001.png'),
  (10, 'Skirk',      'Abyssal swordswoman emphasizing discipline and aggressive tempo.', 'model01010.vrm', '/character-img-01010.png'),
  (11, 'Yelan',      'Hydro operative leveraging mobility, timing, and precision tools.', 'model00000.vrm', '/character-img-00000.png')
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  model_path = excluded.model_path,
  image_path = excluded.image_path;

insert into public.cards (character_id, card_index, name)
select
  c.id,
  gs.card_index,
  c.name || ' Card ' || (gs.card_index + 1)::text
from public.characters c
cross join generate_series(0, 7) as gs(card_index)
on conflict (character_id, card_index) do update
set name = excluded.name;

-- Backfill for existing users created before this migration.
insert into public.profiles (id, email, preferred_model)
select au.id, coalesce(au.email, ''), 'model00000'
from auth.users au
on conflict (id) do update
set
  email = excluded.email,
  preferred_model = coalesce(public.profiles.preferred_model, excluded.preferred_model);

insert into public.user_characters (user_id, character_id, unlocked, unlocked_at)
select p.id, c.id, false, null
from public.profiles p
cross join public.characters c
on conflict (user_id, character_id) do nothing;

insert into public.user_cards (user_id, card_id, unlocked, unlocked_at)
select p.id, c.id, false, null
from public.profiles p
cross join public.cards c
on conflict (user_id, card_id) do nothing;

commit;

-- =========================
-- 6) QUERY EXAMPLES FOR API
-- =========================

-- NOTE:
-- Supabase SQL Editor executes every non-comment statement immediately.
-- Parameter placeholders like $1, $2 only work inside prepared statements/RPC functions,
-- so the examples below are intentionally commented templates.

-- A) Get all characters with unlock status + progress per character
-- Input: :user_id (uuid)
-- select
--   c.id,
--   c.name,
--   c.description,
--   coalesce(uch.unlocked, false) as unlocked,
--   uch.unlocked_at,
--   count(cd.id) filter (where uc.unlocked = true) as cards_unlocked,
--   count(cd.id) as cards_total
-- from public.characters c
-- left join public.user_characters uch
--   on uch.character_id = c.id
--  and uch.user_id = :user_id
-- left join public.cards cd
--   on cd.character_id = c.id
-- left join public.user_cards uc
--   on uc.card_id = cd.id
--  and uc.user_id = :user_id
-- group by c.id, c.name, c.description, uch.unlocked, uch.unlocked_at
-- order by c.id;

-- B) Get all cards for one character with unlock status
-- Input: :user_id (uuid), :character_id (smallint)
-- select
--   cd.id,
--   cd.character_id,
--   cd.card_index,
--   cd.name,
--   coalesce(uc.unlocked, false) as unlocked,
--   uc.unlocked_at
-- from public.cards cd
-- left join public.user_cards uc
--   on uc.card_id = cd.id
--  and uc.user_id = :user_id
-- where cd.character_id = :character_id
-- order by cd.card_index;

-- C) Unlock a card (idempotent)
-- Input: :user_id (uuid), :card_id (int)
-- update public.user_cards
-- set
--   unlocked = true,
--   unlocked_at = coalesce(unlocked_at, timezone('utc', now()))
-- where user_id = :user_id
--   and card_id = :card_id
-- returning id, user_id, card_id, unlocked, unlocked_at;

-- D) Explicit check if a character should unlock for a user
-- Input: :user_id (uuid), :character_id (smallint)
-- select
--   c.character_id,
--   count(*) as total_cards,
--   count(*) filter (where uc.unlocked = true) as unlocked_cards,
--   (count(*) filter (where uc.unlocked = true) = count(*)) as should_unlock
-- from public.cards c
-- join public.user_cards uc
--   on uc.card_id = c.id
--  and uc.user_id = :user_id
-- where c.character_id = :character_id
-- group by c.character_id;

-- E) Force unlock check manually (optional service action)
-- Input: :user_id (uuid), :character_id (smallint)
-- select public.unlock_character_if_completed(:user_id, :character_id);

-- F) Insert play history row
-- Input: :user_id (uuid), :score (int), :puzzles_solved (int), :duration_seconds (int)
-- insert into public.play_history (user_id, score, puzzles_solved, duration_seconds)
-- values (:user_id, :score, :puzzles_solved, :duration_seconds)
-- returning id, user_id, session_date, score, puzzles_solved, duration_seconds;

-- G) User progress summary
-- Input: :user_id (uuid)
-- with card_stats as (
--   select
--     uc.user_id,
--     count(*) filter (where uc.unlocked = true) as total_cards_unlocked
--   from public.user_cards uc
--   where uc.user_id = :user_id
--   group by uc.user_id
-- ),
-- character_stats as (
--   select
--     uch.user_id,
--     count(*) filter (where uch.unlocked = true) as total_characters_unlocked
--   from public.user_characters uch
--   where uch.user_id = :user_id
--   group by uch.user_id
-- ),
-- history_stats as (
--   select
--     ph.user_id,
--     count(*) as total_play_sessions,
--     coalesce(sum(ph.score), 0) as total_score,
--     coalesce(sum(ph.puzzles_solved), 0) as total_puzzles_solved,
--     coalesce(sum(ph.duration_seconds), 0) as total_duration_seconds
--   from public.play_history ph
--   where ph.user_id = :user_id
--   group by ph.user_id
-- )
-- select
--   p.id as user_id,
--   p.email,
--   coalesce(cs.total_cards_unlocked, 0) as total_cards_unlocked,
--   coalesce(chs.total_characters_unlocked, 0) as total_characters_unlocked,
--   coalesce(hs.total_play_sessions, 0) as total_play_sessions,
--   coalesce(hs.total_score, 0) as total_score,
--   coalesce(hs.total_puzzles_solved, 0) as total_puzzles_solved,
--   coalesce(hs.total_duration_seconds, 0) as total_duration_seconds
-- from public.profiles p
-- left join card_stats cs
--   on cs.user_id = p.id
-- left join character_stats chs
--   on chs.user_id = p.id
-- left join history_stats hs
--   on hs.user_id = p.id
-- where p.id = :user_id
-- group by p.id, p.email, cs.total_cards_unlocked, chs.total_characters_unlocked, hs.total_play_sessions, hs.total_score, hs.total_puzzles_solved, hs.total_duration_seconds;

-- =========================
-- 7) OPTIONAL MVP BIT STRING MODEL
-- =========================

-- This compact alternative is acceptable only for MVP prototypes with very small fixed dimensions.
-- Not recommended for long-term production because analytics, joins, and schema evolution are harder.

create table if not exists public.user_progress_bits (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  characters_owned bit(11) not null default B'00000000000',
  cards_owned bit(88) not null default B'0000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_user_progress_bits_user_id on public.user_progress_bits(user_id);

-- =========================
-- Idempotent reconciliation migration
-- Ensures `preferred_model` exists for `profiles` and reconciles static characters
-- Run this block in Supabase SQL Editor if the schema cache reports the column missing.
-- This is safe to run multiple times and will not overwrite manual edits to characters.

begin;

-- 1) Add preferred_model column if it's missing (idempotent)
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'preferred_model'
  ) then
    alter table public.profiles
    add column preferred_model text not null default 'model00000';
  end if;
end$$;

-- 2) Add CHECK constraint for allowed models if missing (non-destructive)
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_preferred_model_allowed'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
    add constraint profiles_preferred_model_allowed check (
      preferred_model in (
        'model00000', 'model00001', 'model00010', 'model00011', 'model00100',
        'model00101', 'model00110', 'model00111', 'model01000', 'model01001',
        'model01010'
      )
    );
  end if;
end$$;

-- 3) Backfill existing profiles with a sensible default where NULL
update public.profiles
set preferred_model = 'model00000'
where preferred_model is null;

-- 4) Ensure static characters exist. This will not overwrite manual edits because it uses
-- ON CONFLICT DO NOTHING. If you want to overwrite, run the earlier seed block in the file
-- (it uses ON CONFLICT DO UPDATE); here we only ensure missing rows are present.
insert into public.characters (id, name, description, model_path, image_path)
values
  (1,  'Arlecchino', 'Crimson tactician with high-risk precision combat style.', 'model00001.vrm', '/character-img-00001.png'),
  (2,  'Charlotte',  'Investigative reporter using sharp insight and support utility.', 'model00010.vrm', '/character-img-00010.png'),
  (3,  'Furina',     'Hydro performer controlling rhythm, pressure, and adaptation.', 'model00011.vrm', '/character-img-00011.png'),
  (4,  'Ganyu',      'Calm cryo archer focused on timing and sustained precision.', 'model00100.vrm', '/character-img-00100.png'),
  (5,  'Keqing',     'Electro duelist built around burst movement and rapid execution.', 'model00101.vrm', '/character-img-00101.png'),
  (6,  'Kokomi',     'Strategic hydro leader with balanced sustain and control.', 'model00110.vrm', '/character-img-00110.png'),
  (7,  'Nahida',     'Dendro analyst linking systems through layered reactions.', 'model00111.vrm', '/character-img-00111.png'),
  (8,  'Navia',      'Geo commander specializing in momentum and tactical shots.', 'model01000.vrm', '/character-img-01000.png'),
  (9,  'Neuvillette','Hydro judge channeling heavy pressure and field dominance.', 'model01001.vrm', '/character-img-01001.png'),
  (10, 'Skirk',      'Abyssal swordswoman emphasizing discipline and aggressive tempo.', 'model01010.vrm', '/character-img-01010.png'),
  (11, 'Yelan',      'Hydro operative leveraging mobility, timing, and precision tools.', 'model00000.vrm', '/character-img-00000.png')
on conflict (id) do nothing;

commit;

